/** Stable machine-readable codes returned alongside human messages. */
export enum ErrorCode {
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS = 'WALLET_ALREADY_EXISTS',
  WALLET_TOKEN_NOT_FOUND = 'WALLET_TOKEN_NOT_FOUND',
  MAXIMUM_WALLET_TOKENS_REACHED = 'MAXIMUM_WALLET_TOKENS_REACHED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  UNAUTHORIZED_WALLET_ACCESS = 'UNAUTHORIZED_WALLET_ACCESS',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  WALLET_TOKEN_EXPIRED = 'WALLET_TOKEN_EXPIRED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
}
